### PR TITLE
Push doesn't collect all objects if multiple blobs use the same hash

### PR DESCRIPTION
**Pull request by SpiralP**
After making a test repo of a bunch of copied and pasted files, then trying to modify one and push using es-git I get a `0055fatal: did not receive expected object 20076e54bbad301d4f0ac236bd594ee0cf37331f`

https://github.com/es-git/es-git/blob/6cfa07a51e9f625935500c0e99693fab0ce46446/packages/push-mixin/ts/index.ts#L39

Also thanks for such a great library!

### CODE REVIEW

**Comment by mariusGundersen** [comment]
Hmm, the idea behind this is to not add duplicates. So when walking a tree, if the tree has already been added to the map then there is no point in adding the subtrees, since they too must have been added to the map. It's a performance improvement only, since the map cannot store duplicates, so I'm willing to accept this pull-request, but I would prefer to understand why the code isn't working correctly today.

**Comment by mariusGundersen** [comment]
oh, it's breaking out of the whole treeWalking, not just the current subtree...

I guess the walkTree method needs to handle feedback better, so that it can skip a subtree but continue walking the siblings

**Comment by mariusGundersen** [comment]
I've implemented a better walker in v0.3.2, please try it and see if things have improved

**Comment by SpiralP** [comment]
Yup, everything works now, thanks!

**Pull request merged**
